version: "3"
services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:6
    ports:
      - "0.0.0.0:1935:1935"
      - "0.0.0.0:8080:8080"
    command: ./objs/srs -c conf/hevc.flv.conf
    networks:
      - bridge
  ffmpeg:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:encoder
    volumes:
      - "/Users/das/Desktop/code/node-media-rtmp-server/srs/doc:/usr/local/srs/doc"
    # command: ffmpeg -stream_loop -1 -re -i doc/source.flv -acodec copy -vcodec libx265 -f flv rtmp://host.docker.internal/live/livestream
    command: ffmpeg -stream_loop -1 -re -i doc/911Mothers_2010W-480p.mp4 -acodec copy -vcodec libx264 -f flv rtmp://host.docker.internal/live/livestream
    # command: ffmpeg -stream_loop -1 -re -i doc/h265.mp4 -acodec copy -vcodec copy -f flv rtmp://host.docker.internal/live/livestream
    depends_on:
      - srs

networks:
  bridge:
    driver: bridge
